### ISSUE TITLE
What's the state of this?

### ISSUE THREAD

**Issue by markushausammann** [alessandropietrobelli/AP_XmlStrategy#4]
Hi, I just wanted to ask about the state of this project. There are no tagged releases and development has stopped. Is it compatible with the latest ZF2 versions? Are you using it in a project in production?

**Comment by webdevilopers** [comment]
Good question!

**Comment by alessandropietrobelli** [comment]
Hi All,
sorry I'm late, I don't know if it is still compatible with the latest ZF2 versions, you can try, maybe in the next weeks I could test it on the latest version.

Bye!

**Comment by paulocoliver** [comment]
Add in module.config.php

``` php
'strategies' => array(
        'ViewJsonStrategy',
        'ViewFeedStrategy',
        'ViewXmlStrategy'
),
```

**Comment by jsundquist** [comment]
This is still compatible with the current version of Zend Framework 2? When will you be tagging it as stable?

There are still some minor items that need to be address, specifically in the https://github.com/alessandropietrobelli/AP_XmlStrategy/blob/master/src/AP_XmlStrategy/View/Renderer/XmlRenderer.php#L75 where it states the JsonStrategy.

**Comment by alessandropietrobelli** [comment]
Hi, this package is not longer maintained, I'd stop programming with ZF2 about 1 year ago, sorry!

**Comment by jsundquist** [comment]
Thank you for the update.
